//! `cargo xtask plugin new` — scaffold a WASI Preview 2 component plugin.
//!
//! The scaffold produces exactly what the fleet ships: a `cdylib` built for
//! `wasm32-wasip2`, its family world generated by `wit-bindgen` from WIT
//! vendored in the plugin crate, and the PDK's family entry macro wiring the
//! `describe`/`process` exports to a descriptor factory and a typed command
//! handler. There is no Preview 1 / Extism scaffold any more: that shape
//! cannot be loaded by any current Scryer host.
//!
//! Only the notification family is scaffolded today. The other four families
//! differ in their world, their WIT package and their command enum, and a
//! wrong-shaped scaffold is worse than none — so they report what to copy
//! instead of generating something that does not build.

use anyhow::{Context, Result, bail};
use std::fs;
use std::path::{Path, PathBuf};

use crate::{
    PluginKindArg, PluginNewArgs, SdkDependency, TaskContext, current_sdk_dependency, ok,
    repo_cargo_command_in, run_checked,
};

const NOTIFICATION_LIB_RS_TEMPLATE: &str =
    include_str!("../templates/plugin_new/notification/lib.rs.tpl");

/// The WIT packages a notification component's `wit/` directory must carry.
///
/// They are copied from a sibling plugin in the same family rather than
/// vendored into `xtask`, so a scaffold can never drift from the contract the
/// family actually ships.
const NOTIFICATION_WIT_PACKAGES: [&str; 2] = ["host-v1.0.0", "notification-v1.0.0"];

/// The Scryer floor for a component plugin.
///
/// A Preview 1 host cannot instantiate a component at all, so a new plugin has
/// to declare the first release whose family host is component-backed. This is
/// the same placeholder the first-party components carry; replace it with the
/// real release when one ships.
const COMPONENT_MIN_SCRYER_VERSION: &str = "0.18.23";

const WIT_BINDGEN_VERSION: &str = "0.61";
const PDK_PATH_FROM_PLUGIN: &str = "../../pdk/scryer-plugin-pdk";
const PDK_VERSION: &str = "0.6.0";

pub(crate) fn run_plugin_new(ctx: &TaskContext, args: PluginNewArgs) -> Result<()> {
    let plugin_dir = scaffold_plugin(ctx, &ctx.repo_root, args.kind, &args.name)?;
    ok(format!("Created {}", plugin_dir.display()));
    Ok(())
}

fn scaffold_plugin(
    ctx: &TaskContext,
    repo_root: &Path,
    kind: PluginKindArg,
    name: &str,
) -> Result<PathBuf> {
    let spec = ScaffoldSpec::new(kind, name)?;
    let family_dir = repo_root.join(spec.kind.directory());
    let plugin_dir = family_dir.join(&spec.plugin_id);
    if plugin_dir.exists() {
        bail!("{} already exists", plugin_dir.display());
    }

    fs::create_dir_all(plugin_dir.join("src"))?;
    let scaffold_result = (|| -> Result<()> {
        copy_family_wit(&family_dir, &plugin_dir, spec.kind)?;
        fs::write(
            plugin_dir.join("Cargo.toml"),
            spec.render_manifest(&current_sdk_dependency(ctx)?),
        )?;
        fs::write(plugin_dir.join("src/lib.rs"), spec.render_lib_rs()?)?;
        format_generated_crate(ctx, &plugin_dir)?;
        Ok(())
    })();

    if let Err(error) = scaffold_result {
        let _ = fs::remove_dir_all(&plugin_dir);
        return Err(error);
    }

    Ok(plugin_dir)
}

/// Copy the family's WIT packages from a sibling plugin into the new crate.
///
/// `wit-bindgen` resolves the world out of the crate's own `wit/`, so every
/// component vendors the same packages. Taking them from a sibling — the first
/// one, in directory order, that carries a complete set — keeps a scaffold
/// byte-identical to the contract the family is shipping right now.
fn copy_family_wit(family_dir: &Path, plugin_dir: &Path, kind: PluginKindArg) -> Result<()> {
    let packages = kind.wit_packages();
    let source = family_wit_source(family_dir, packages).ok_or_else(|| {
        anyhow::anyhow!(
            "no plugin under {} carries a complete wit/ directory ({}); cannot scaffold a {} component",
            family_dir.display(),
            packages.join(", "),
            kind.directory()
        )
    })?;

    for package in packages {
        let from = source.join(package);
        let to = plugin_dir.join("wit").join(package);
        fs::create_dir_all(&to)?;
        for entry in fs::read_dir(&from)
            .with_context(|| format!("failed to read WIT package {}", from.display()))?
        {
            let entry = entry?;
            if entry.file_type()?.is_file() {
                fs::copy(entry.path(), to.join(entry.file_name())).with_context(|| {
                    format!(
                        "failed to copy {} into the scaffold",
                        entry.path().display()
                    )
                })?;
            }
        }
    }
    Ok(())
}

fn family_wit_source(family_dir: &Path, packages: &[&str]) -> Option<PathBuf> {
    let mut candidates = fs::read_dir(family_dir)
        .ok()?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path().join("wit"))
        .filter(|wit| packages.iter().all(|package| wit.join(package).is_dir()))
        .collect::<Vec<_>>();
    candidates.sort();
    candidates.into_iter().next()
}

fn format_generated_crate(ctx: &TaskContext, plugin_dir: &Path) -> Result<()> {
    let mut fmt = repo_cargo_command_in(ctx, plugin_dir)?;
    fmt.args(["fmt", "--manifest-path", "Cargo.toml"]);
    run_checked(&mut fmt).context("failed to format generated plugin scaffold")
}

#[derive(Clone, Debug)]
struct ScaffoldSpec {
    kind: PluginKindArg,
    plugin_id: String,
    crate_name: String,
}

impl ScaffoldSpec {
    fn new(kind: PluginKindArg, name: &str) -> Result<Self> {
        kind.ensure_scaffoldable()?;
        let plugin_id = normalize_plugin_name(name)?;
        let crate_name = format!("{}_{}", plugin_id.replace('-', "_"), kind.crate_suffix());
        Ok(Self {
            kind,
            plugin_id,
            crate_name,
        })
    }

    fn render_lib_rs(&self) -> Result<String> {
        render_template(
            "lib.rs",
            self.kind.lib_rs_template(),
            &[("plugin_id", &self.plugin_id)],
        )
    }

    /// Render the scaffold's `Cargo.toml`.
    ///
    /// Written as text rather than assembled with `toml_edit` so the file a
    /// contributor opens has real section headers and the comments that explain
    /// the two settings they are most likely to get wrong. It is parsed back in
    /// the tests, so a malformed template fails there.
    fn render_manifest(&self, sdk: &SdkDependency) -> String {
        let repo_path = format!("{}/{}", self.kind.directory(), self.plugin_id);
        let source_url = format!("https://github.com/OWNER/REPO/tree/main/{repo_path}");
        format!(
            r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[package.metadata.scryer]
official = false
plugin_id = "{plugin_id}"
catalog_versions = ["v3"]
# A Preview 1 host cannot instantiate a component, so a component plugin has to
# declare the first Scryer whose family host is component-backed.
min_scryer_version = "{min_scryer_version}"
feature_sets = [{{ required_features = [] }}]
docs_url = "{source_url}"
source_repo = "{source_url}"

# A component is a `cdylib`; the PDK entry macro supplies `describe`/`process`.
[lib]
crate-type = ["cdylib"]

[dependencies]
scryer-plugin-pdk = {{ path = "{pdk_path}", version = "{pdk_version}" }}
scryer-plugin-sdk = {sdk_dependency}
serde_json = "1"
wit-bindgen = "{wit_bindgen_version}"

# `cargo xtask plugin validate` builds this profile, and the host rejects an
# artifact that unwinds.
[profile.plugin-release]
inherits = "release"
opt-level = 3
lto = "fat"
strip = true
panic = "abort"
"#,
            crate_name = self.crate_name,
            plugin_id = self.plugin_id,
            min_scryer_version = COMPONENT_MIN_SCRYER_VERSION,
            source_url = source_url,
            pdk_path = PDK_PATH_FROM_PLUGIN,
            pdk_version = PDK_VERSION,
            sdk_dependency = render_sdk_dependency(sdk),
            wit_bindgen_version = WIT_BINDGEN_VERSION,
        )
    }
}

/// Render the scaffold's `scryer-plugin-sdk` line in whatever form xtask itself
/// uses.
///
/// The fleet currently resolves the SDK from a git ref, and a scaffold that
/// asked crates.io for it would not build. Rather than hard-code that URL a
/// second time, the form is derived from `xtask/Cargo.toml`, so a scaffold
/// generated after the SDK is published again gets the plain version form.
fn render_sdk_dependency(sdk: &SdkDependency) -> String {
    match sdk {
        SdkDependency::Published(version) => format!("\"{version}\""),
        SdkDependency::Git {
            url,
            reference,
            version,
        } => format!(
            "{{ git = \"{url}\", {} = \"{}\", version = \"{version}\" }}",
            reference.key, reference.value
        ),
    }
}

fn normalize_plugin_name(name: &str) -> Result<String> {
    let normalized = name
        .trim()
        .to_ascii_lowercase()
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '-' })
        .collect::<String>()
        .split('-')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("-");
    if normalized.is_empty() {
        bail!("plugin name must contain at least one ASCII letter or digit");
    }
    Ok(normalized)
}

fn render_template(
    template_name: &str,
    template: &str,
    replacements: &[(&str, &str)],
) -> Result<String> {
    let mut rendered = template.to_string();
    for (key, value) in replacements {
        rendered = rendered.replace(&format!("{{{{{key}}}}}"), value);
    }

    if rendered.contains("{{") || rendered.contains("}}") {
        bail!("template {template_name} has unreplaced placeholders");
    }

    Ok(rendered.trim_start().to_string())
}

impl PluginKindArg {
    fn directory(self) -> &'static str {
        match self {
            Self::Indexer => "indexers",
            Self::DownloadClient => "download_clients",
            Self::Notification => "notifications",
            Self::Subtitle => "subtitles",
            Self::ArchiveExtractor => "archive_extractors",
        }
    }

    fn crate_suffix(self) -> &'static str {
        match self {
            Self::Indexer => "indexer",
            Self::DownloadClient => "download_client",
            Self::Notification => "notification",
            Self::Subtitle => "subtitle_provider",
            Self::ArchiveExtractor => "archive_extractor",
        }
    }

    /// The reference plugin a family's scaffold should be copied from by hand.
    fn reference_plugin(self) -> &'static str {
        match self {
            Self::Indexer => "indexers/newznab",
            Self::DownloadClient => "download_clients/qbittorrent",
            Self::Notification => "notifications/gotify",
            Self::Subtitle => "subtitles/opensubtitles",
            Self::ArchiveExtractor => "archive_extractors/archive-extraction",
        }
    }

    fn ensure_scaffoldable(self) -> Result<()> {
        if matches!(self, Self::Notification) {
            return Ok(());
        }
        bail!(
            "`plugin new` scaffolds notification components only. The {} family has its own world, \
WIT package and command enum, so copy `{}` — its Cargo.toml, its `wit/` directory, its \
`wit_bindgen::generate!` block and its family entry macro — and rename it instead.",
            self.directory(),
            self.reference_plugin()
        )
    }

    fn wit_packages(self) -> &'static [&'static str] {
        match self {
            Self::Notification => &NOTIFICATION_WIT_PACKAGES,
            // Unreachable while `ensure_scaffoldable` gates everything else.
            _ => &[],
        }
    }

    fn lib_rs_template(self) -> &'static str {
        match self {
            Self::Notification => NOTIFICATION_LIB_RS_TEMPLATE,
            _ => "",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use std::time::{SystemTime, UNIX_EPOCH};
    use toml_edit::DocumentMut;

    /// The SDK declaration the scaffold has to mirror, read from the real
    /// `xtask/Cargo.toml` so the test tracks the fleet instead of restating it.
    fn test_sdk_dependency() -> SdkDependency {
        crate::sdk_dependency_from_manifest(
            &PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("Cargo.toml"),
        )
        .expect("read the xtask SDK dependency")
    }

    fn temp_task_context() -> (tempfile::TempDir, TaskContext) {
        let temp_dir = tempfile::tempdir().expect("create tempdir");
        let repo_dir = temp_dir.path().join("repo");
        fs::create_dir_all(&repo_dir).expect("create repo dir");
        (
            temp_dir,
            TaskContext {
                repo_root: repo_dir,
            },
        )
    }

    /// The scaffold must produce a component, not a Preview 1 command plugin.
    #[test]
    fn render_lib_rs_produces_a_component_entry_point() {
        let spec =
            ScaffoldSpec::new(PluginKindArg::Notification, "Example Plugin").expect("build spec");
        let lib_rs = spec.render_lib_rs().expect("render lib.rs");

        assert!(lib_rs.contains("wit_bindgen::generate!"));
        assert!(lib_rs.contains("scryer:notification/notification@1.0.0"));
        assert!(lib_rs.contains("scryer_plugin_pdk::scryer_notification_component_main!"));
        assert!(lib_rs.contains("ProviderDescriptor::Notification(NotificationDescriptor {"));
        assert!(!lib_rs.contains("extism"));
        assert!(!lib_rs.contains("plugin_fn"));
        assert!(
            !lib_rs.contains("{{") && !lib_rs.contains("}}"),
            "left template placeholders behind"
        );
    }

    #[test]
    fn non_notification_families_report_what_to_copy() {
        for kind in [
            PluginKindArg::Indexer,
            PluginKindArg::DownloadClient,
            PluginKindArg::Subtitle,
            PluginKindArg::ArchiveExtractor,
        ] {
            let error = ScaffoldSpec::new(kind, "Example Plugin")
                .expect_err("only notifications are scaffolded");
            let message = error.to_string();
            assert!(
                message.contains(kind.reference_plugin()),
                "{kind:?} should name its reference plugin, got: {message}"
            );
        }
    }

    #[test]
    fn render_manifest_marks_new_plugins_as_non_official() {
        let spec = ScaffoldSpec::new(PluginKindArg::Notification, "Example Plugin")
            .expect("build scaffold spec");
        let manifest = spec.render_manifest(&test_sdk_dependency());
        let document = manifest.parse::<DocumentMut>().expect("parse manifest");

        assert_eq!(
            document["package"]["metadata"]["scryer"]["official"].as_bool(),
            Some(false)
        );
    }

    #[test]
    fn render_manifest_contains_expected_package_contract() {
        let spec =
            ScaffoldSpec::new(PluginKindArg::Notification, "Webhook Example").expect("build spec");
        let sdk = test_sdk_dependency();
        let manifest = spec.render_manifest(&sdk);
        let document = manifest.parse::<DocumentMut>().expect("parse manifest");

        assert_eq!(
            document["package"]["name"].as_str(),
            Some("webhook_example_notification")
        );
        assert_eq!(document["package"]["version"].as_str(), Some("0.1.0"));
        assert_eq!(document["package"]["edition"].as_str(), Some("2024"));
        assert_eq!(document["lib"]["crate-type"][0].as_str(), Some("cdylib"));
        assert!(
            document["dependencies"].get("extism-pdk").is_none(),
            "the scaffold must not depend on extism-pdk"
        );
        assert_eq!(
            document["dependencies"]["scryer-plugin-pdk"]["version"].as_str(),
            Some(PDK_VERSION)
        );
        assert_eq!(
            document["dependencies"]["wit-bindgen"].as_str(),
            Some(WIT_BINDGEN_VERSION)
        );
        // The scaffold must declare the SDK exactly the way xtask/Cargo.toml
        // does: a crates.io form would not resolve while the fleet is on the
        // git ref, and the URL must never be spelled out a second time.
        let scaffolded = &document["dependencies"]["scryer-plugin-sdk"];
        match &sdk {
            SdkDependency::Published(version) => {
                assert_eq!(scaffolded.as_str(), Some(version.as_str()));
            }
            SdkDependency::Git {
                url,
                reference,
                version,
            } => {
                assert_eq!(
                    scaffolded.get("git").and_then(|item| item.as_str()),
                    Some(url.as_str())
                );
                assert_eq!(
                    scaffolded
                        .get(reference.key.as_str())
                        .and_then(|item| item.as_str()),
                    Some(reference.value.as_str())
                );
                assert_eq!(
                    scaffolded.get("version").and_then(|item| item.as_str()),
                    Some(version.as_str())
                );
            }
        }
        assert_eq!(document["dependencies"]["serde_json"].as_str(), Some("1"));
        assert!(manifest.contains("feature_sets = [{ required_features = [] }]"));
        // catalog-v2 publishing is retired, and a manifest that still asks for
        // it is rejected by `reject_retired_catalog_v2_metadata`.
        assert_eq!(
            document["package"]["metadata"]["scryer"]["catalog_versions"][0].as_str(),
            Some("v3")
        );
        assert_eq!(
            document["package"]["metadata"]["scryer"]["catalog_versions"]
                .as_array()
                .map(|versions| versions.len()),
            Some(1)
        );
        assert_eq!(
            document["profile"]["plugin-release"]["inherits"].as_str(),
            Some("release")
        );
        assert_eq!(
            document["profile"]["plugin-release"]["panic"].as_str(),
            Some("abort")
        );
        assert!(
            document["package"]["metadata"]["scryer"]
                .as_table()
                .and_then(|metadata| metadata.get("distribution_base_url"))
                .is_none(),
            "new plugin manifests should use the computed first-party distribution URL"
        );
    }

    #[test]
    fn scaffold_plugin_writes_files_and_formats_generated_crate() {
        let (temp_dir, ctx) = temp_task_context();
        // The repository's own pin, not a literal: the scaffold is formatted
        // with the toolchain `xtask` selects, and a stale channel here fails on
        // a missing `rustfmt` component rather than on anything about the
        // scaffold.
        fs::write(
            ctx.repo_root.join("rust-toolchain.toml"),
            include_str!("../../rust-toolchain.toml"),
        )
        .expect("write toolchain file");

        // The scaffold copies its `scryer-plugin-sdk` declaration out of
        // `xtask/Cargo.toml`, so the temp repo carries the real one rather than
        // a fixture that could drift from what the fleet actually resolves.
        fs::create_dir_all(ctx.repo_root.join("xtask")).expect("create xtask dir");
        fs::write(
            ctx.repo_root.join("xtask/Cargo.toml"),
            include_str!("../Cargo.toml"),
        )
        .expect("write xtask manifest");

        // A sibling plugin supplies the family WIT, exactly as in the repo.
        let sibling_wit = ctx.repo_root.join("notifications/reference/wit");
        for package in NOTIFICATION_WIT_PACKAGES {
            fs::create_dir_all(sibling_wit.join(package)).expect("create sibling wit package");
            fs::write(
                sibling_wit.join(package).join("contract.wit"),
                format!("// {package}\n"),
            )
            .expect("write sibling wit");
        }

        let seed = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time before unix epoch")
            .as_nanos();
        let plugin_name = format!("Scaffold Test {seed}");
        let plugin_dir = scaffold_plugin(
            &ctx,
            &ctx.repo_root,
            PluginKindArg::Notification,
            &plugin_name,
        )
        .expect("scaffold plugin");

        let cargo_toml = plugin_dir.join("Cargo.toml");
        let lib_rs = plugin_dir.join("src/lib.rs");
        assert!(cargo_toml.is_file(), "Cargo.toml should exist");
        assert!(lib_rs.is_file(), "src/lib.rs should exist");
        for package in NOTIFICATION_WIT_PACKAGES {
            assert!(
                plugin_dir
                    .join("wit")
                    .join(package)
                    .join("contract.wit")
                    .is_file(),
                "{package} should be vendored into the scaffold"
            );
        }

        let mut fmt_check = repo_cargo_command_in(&ctx, &plugin_dir).expect("cargo fmt command");
        fmt_check.args(["fmt", "--check", "--manifest-path", "Cargo.toml"]);
        run_checked(&mut fmt_check).expect("generated crate should be fmt clean");

        drop(temp_dir);
    }
}
