//! {{plugin_id}} subtitle provider, as a WASI Preview 2 component.
//!
//! The two exports Scryer calls — `describe` and `process` — are generated by
//! the PDK's entry macro below. `describe` returns [`build_descriptor`] and is
//! synchronous; every `process` call arrives here as a typed
//! [`PluginSubtitleCommand`] on an **`async fn`**, because
//! `scryer:subtitle@1.1.0` lifts `process` as an `async func`. Awaiting a host
//! call yields the guest task back to the host instead of blocking the store,
//! so a provider may hold a request open across an HTTP round trip or a sleep.
//!
//! Two import packages back that:
//!
//! * `scryer:host/services@1.0.0` — the single encoded door for everything the
//!   SDK models as a postcard request (config, plugin state, HTTP, archive
//!   extraction). Reach it through `scryer_plugin_pdk::config`, `::var` and
//!   `::http`, never `std::net` or `wasi:http`: only the PDK path is checked
//!   against this plugin's descriptor permissions.
//! * `scryer:runtime/host@1.0.0` — the family-neutral *typed* capability
//!   surface: `scryer_plugin_pdk::runtime::{http, sleep, monotonic_now_ms,
//!   operation_deadline_monotonic_ms, state_get, state_cas, log}`. These are
//!   the ones that must be awaited; the import only appears in the built
//!   artifact if reachable code actually names one.
//!
//! Every operational failure is reported in-band through [`PluginResult`] —
//! including "this provider does not do that", which is
//! [`PluginErrorCode::Unsupported`], not a trap. A world-level
//! `invocation-error` means the component itself is broken.

use scryer_plugin_pdk::sdk::{
    PluginDescriptor, PluginError, PluginErrorCode, PluginResult, ProviderDescriptor, SDK_VERSION,
    SubtitleCapabilities, SubtitlePluginSearchResponse, SubtitlePluginValidateConfigResponse,
    SubtitleProviderMode, SubtitleQueryMediaKind, SubtitleValidateConfigStatus,
    current_sdk_constraint,
};
use scryer_plugin_pdk::{PluginSubtitleCommand, PluginSubtitleCommandResult};

wit_bindgen::generate!({
    // Fully qualified: `path` resolves three packages, so a bare world name is
    // ambiguous even though only one of them declares a world.
    world: "scryer:subtitle/subtitle-provider@1.1.0",
    // Three packages, three paths, matching the host's own bindgen: the two
    // imported packages are listed first so the family package's
    // `import scryer:host/services@1.0.0` and
    // `import scryer:runtime/host@1.0.0` resolve against them.
    path: ["wit/host-v1.0.0", "wit/runtime-v1.0.0", "wit/subtitle-v1.1.0"],
    // The imported packages live in their own WIT packages, so wit-bindgen asks
    // explicitly whether to generate for them. Yes: the PDK holds only a `fn`
    // pointer and a runtime backend, and the entry macro binds them to this
    // module's generated imports.
    generate_all,
});

scryer_plugin_pdk::scryer_subtitle_component_main!(
    descriptor = build_descriptor,
    handler = handle_subtitle_command,
);

const PROVIDER_TYPE: &str = "{{plugin_id}}";

fn build_descriptor() -> PluginDescriptor {
    PluginDescriptor {
        id: PROVIDER_TYPE.to_string(),
        name: PROVIDER_TYPE.to_string(),
        version: env!("CARGO_PKG_VERSION").to_string(),
        sdk_version: SDK_VERSION.to_string(),
        sdk_constraint: current_sdk_constraint(),
        // Subtitle providers reach their upstream over HTTP; raw sockets are a
        // notification-family concern.
        socket_permissions: vec![],
        provider: ProviderDescriptor::Subtitle(scryer_plugin_pdk::sdk::SubtitleDescriptor {
            provider_type: PROVIDER_TYPE.to_string(),
            provider_aliases: vec![],
            default_base_url: None,
            // Every host this provider may reach. The host rejects a request to
            // anything not listed here, so an empty list means no outbound
            // requests at all.
            allowed_hosts: vec![],
            capabilities: SubtitleCapabilities {
                mode: SubtitleProviderMode::Catalog,
                supported_media_kinds: vec![
                    SubtitleQueryMediaKind::Movie,
                    SubtitleQueryMediaKind::Episode,
                ],
                ..SubtitleCapabilities::default()
            },
            config_fields: vec![],
        }),
    }
}

/// One `process` invocation, dispatched by operation.
///
/// `async` because the world lifts `process` as an `async func`: awaiting a
/// `scryer_plugin_pdk::runtime` call here is what lets the host run other work
/// while this provider waits on its upstream.
async fn handle_subtitle_command(command: PluginSubtitleCommand) -> PluginSubtitleCommandResult {
    match command {
        PluginSubtitleCommand::ValidateConfig(_request) => {
            // TODO: probe the provider with the configured credentials and map
            // the answer onto `SubtitleValidateConfigStatus` — `AuthFailed`,
            // `RateLimited` and `Unreachable` are all different operator-facing
            // problems and should not collapse into one.
            PluginSubtitleCommandResult::ValidateConfig(PluginResult::Ok(
                SubtitlePluginValidateConfigResponse {
                    status: SubtitleValidateConfigStatus::Valid,
                    message: None,
                    retry_after_seconds: None,
                },
            ))
        }
        PluginSubtitleCommand::Search(_request) => {
            // TODO: query the provider — `runtime::http(...).await` — and map
            // each hit onto a `SubtitlePluginCandidate`. An empty result set is
            // a successful search, not an error.
            PluginSubtitleCommandResult::Search(PluginResult::Ok(SubtitlePluginSearchResponse {
                results: vec![],
            }))
        }
        PluginSubtitleCommand::Download(_request) => {
            // TODO: fetch `provider_file_id` and return the bytes base64-encoded
            // with the container's real `format`. Forward an archive as-is;
            // Scryer's own extraction step opens it.
            PluginSubtitleCommandResult::Download(PluginResult::Err(unsupported(
                "download is not implemented yet",
            )))
        }
        // A catalog provider neither generates nor aligns. Both refusals are
        // in-band `Unsupported` so the host can route around this provider
        // rather than treating the component as broken.
        PluginSubtitleCommand::Generate(_request) => PluginSubtitleCommandResult::Generate(
            PluginResult::Err(unsupported("this is a catalog provider and cannot generate")),
        ),
        PluginSubtitleCommand::Sync(_request) => PluginSubtitleCommandResult::Sync(
            PluginResult::Err(unsupported("this is a catalog provider and cannot align")),
        ),
    }
}

fn unsupported(message: &str) -> PluginError {
    PluginError {
        code: PluginErrorCode::Unsupported,
        public_message: format!("{PROVIDER_TYPE}: {message}"),
        debug_message: None,
        retry_after_seconds: None,
        details: None,
    }
}
