//! {{plugin_id}} notification channel, as a WASI Preview 2 component.
//!
//! The two exports Scryer calls — `describe` and `process` — are generated by
//! the PDK's entry macro below. `describe` returns [`build_descriptor`]; every
//! `process` call arrives here as a typed [`PluginNotificationCommand`].
//!
//! Host services (configuration, HTTP, plugin state, and — for this family
//! only — sockets and host process execution) reach the guest through
//! `scryer:host/services@1.0.0`, which the entry macro installs before any code
//! here runs. Use `scryer_plugin_pdk::config`, `::var` and `::http` rather than
//! reaching for `std::net` or `wasi:http`: only the PDK path is checked against
//! this plugin's descriptor permissions.

use scryer_plugin_pdk::sdk::{
    NotificationCapabilities, NotificationDescriptor, PluginDescriptor, PluginError,
    PluginErrorCode, PluginNotificationResponse, PluginResult, ProviderDescriptor, SDK_VERSION,
    current_sdk_constraint,
};
use scryer_plugin_pdk::{PluginNotificationCommand, PluginNotificationCommandResult};

wit_bindgen::generate!({
    // Fully qualified: `path` resolves two packages, so a bare world name is
    // ambiguous even though only one of them declares a world.
    world: "scryer:notification/notification@1.0.0",
    // Two packages, two paths, matching the host's own bindgen: the shared
    // `scryer:host` package is listed first so the family package's
    // `import scryer:host/services@1.0.0` resolves against it.
    path: ["wit/host-v1.0.0", "wit/notification-v1.0.0"],
    // The shared host package lives in its own WIT package, so wit-bindgen asks
    // explicitly whether to generate for it. Yes: the PDK holds only a `fn`
    // pointer and the entry macro binds it to this module's
    // `scryer::host::services::host-call`.
    generate_all,
});

scryer_plugin_pdk::scryer_notification_component_main!(
    descriptor = build_descriptor,
    handler = handle_notification_command,
);

const PROVIDER_TYPE: &str = "{{plugin_id}}";

fn build_descriptor() -> PluginDescriptor {
    PluginDescriptor {
        id: PROVIDER_TYPE.to_string(),
        name: PROVIDER_TYPE.to_string(),
        version: env!("CARGO_PKG_VERSION").to_string(),
        sdk_version: SDK_VERSION.to_string(),
        sdk_constraint: current_sdk_constraint(),
        // Only an SMTP-style channel needs these; an HTTP channel leaves them
        // empty and reaches its provider through `scryer_plugin_pdk::http`.
        socket_permissions: vec![],
        provider: ProviderDescriptor::Notification(NotificationDescriptor {
            provider_type: PROVIDER_TYPE.to_string(),
            provider_aliases: vec![],
            default_base_url: None,
            // Every host this channel may reach. An empty list means the plugin
            // makes no outbound requests at all.
            allowed_hosts: vec![],
            capabilities: NotificationCapabilities::default(),
            config_fields: vec![],
        }),
    }
}

fn handle_notification_command(
    command: PluginNotificationCommand,
) -> PluginNotificationCommandResult {
    match command {
        PluginNotificationCommand::Send(_request) => {
            // TODO: deliver the notification and report the provider's answer.
            // Report a configuration problem as a typed `PluginError` naming the
            // field, not as a delivery failure.
            PluginNotificationCommandResult::Send(PluginResult::Ok(PluginNotificationResponse {
                success: true,
                error: None,
                delivery_id: None,
                provider_status: None,
                retry_after_seconds: None,
                warnings: vec![],
                target_results: vec![],
            }))
        }
        PluginNotificationCommand::Action(_request) => {
            PluginNotificationCommandResult::Action(PluginResult::Err(PluginError {
                code: PluginErrorCode::Unsupported,
                public_message: format!("{PROVIDER_TYPE} does not implement notification actions"),
                debug_message: None,
                retry_after_seconds: None,
                details: None,
            }))
        }
    }
}
